dataset:
  name: enterprise-explorers/oxford-pets

model:
  name: openai/clip-vit-base-patch32
  lora:
    mode: with_lora          # with_lora | without_lora | both | with_sora_no_schedule | with_sora_schedule
    r: 16
    alpha: 32
    dropout: 0.05
    bias: none
    target_modules:
      - q_proj
      - k_proj
      - v_proj
      - out_proj
  sora:
    sparse_lambda: 10
    sparse_lambda_2: 3.0e-4
    sparse_lr: null
    lambda_schedule: linear
    max_lambda: 1.0
    lambda_num: 5
    schedule_epochs: 15

training:
  batch_size: 32
  epochs: 3
  test_size: 0.2
  seed: 42

optimizer:
  lr: 0.0005
  weight_decay: 0.01

scheduler:
  step_size: 1
  gamma: 0.7

output:
  weights_path: clip_pets_finetuned.pth
