dataset:
  name: enterprise-explorers/oxford-pets

model:
  name: openai/clip-vit-base-patch32
  lora:
    mode: with_sora-pld_schedule    # with_lora-pld | with_lora | without_lora | both | with_sora_no_schedule | with_sora-pld_schedule
    r: 8
    alpha: 32
    dropout: 0.05
    bias: none
    target_modules:
      - q_proj
      - k_proj
      - v_proj
      - out_proj
  paca:                     # ← NOVO
    enabled: true
    upper_layers: 6        # últimas 6 camadas do encoder (de 12 no ViT-B)
    # upper_layers: null    # se quiser desabilitar
  pld:
    enabled: true
    pld_limit: 12  # Camadas que o PLD vai utilizar
  sora:
    sparse_lambda: 0.001
    sparse_lambda_2: 3.0e-4
    sparse_lr: null
    lambda_schedule: linear
    max_lambda: 7.0e-4
    lambda_num: 2
    schedule_epochs: 1
    pre_prune_ratio: 0.25   # 50% dos ranks serão removidos antes do treino
  
training:
  batch_size: 32
  epochs: 10
  test_size: 0.2
  seed: 42

optimizer:
  lr: 0.0005
  weight_decay: 0.01

scheduler:
  step_size: 1
  gamma: 0.7

output:
  weights_path: clip_pets_finetuned.pth
  metrics: training_metrics.json
